# Stage 1: Build the React application
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
RUN cp src/main.blue.jsx src/main.jsx
RUN npm run build

# Stage 2: Serve the application using Nginx
# Stage 2: Serve the application using Nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx/nginx.blue.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
CMD wget --spider -q http://127.0.0.1 || exit 1