services:
  backend:
    image: adithiya123/deployflow-backend:latest
    build:
      context: ./backend
    container_name: deployflow-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: adithiya123/deployflow-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: deployflow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped